# Generated by Django 5.1.15 on 2026-07-21 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file asset", upload_to="uploads/%Y/%m/%d/"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                (
                    "mime_type",
                    models.CharField(blank=True, help_text="MIME type", max_length=100),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="File size in bytes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Media Asset",
                "verbose_name_plural": "Media Assets",
                "db_table": "media_assets",
                "ordering": ["-created_at"],
            },
        ),
    ]
