# Generated by Django 5.1.15 on 2026-07-21 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_members", models.IntegerField(default=0)),
                ("approved_members", models.IntegerField(default=0)),
                ("pending_members", models.IntegerField(default=0)),
                ("suspended_members", models.IntegerField(default=0)),
                (
                    "total_donations_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="organization.district",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="organization.state",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regional Stats",
                "verbose_name_plural": "Regional Stats",
                "db_table": "analytics_regional_stats",
            },
        ),
    ]
