# Generated by Django 5.1.15 on 2026-07-21 13:04

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public-facing unique identifier",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft-delete status flag",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "membership_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique Member Serial ID (e.g., BVS-MH-PUN-001001)",
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="First Name", max_length=100),
                ),
                ("last_name", models.CharField(help_text="Last Name", max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="MALE",
                        max_length=10,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(help_text="Birth Date (Must be age >= 18)"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="10-digit Indian phone number",
                        max_length=15,
                        unique=True,
                        validators=[
                            apps.common.validators.validate_indian_phone_number
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional member email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Membership approval status",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        help_text="District node",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="organization.district",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        help_text="State node",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="organization.state",
                    ),
                ),
                (
                    "taluka",
                    models.ForeignKey(
                        help_text="Taluka node",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="organization.taluka",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked authentication identity account",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        help_text="Village node",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="organization.village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "db_table": "members_member",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PHOTO", "Profile Photo"),
                            ("AADHAAR", "Aadhaar Card"),
                            ("PAN", "PAN Card"),
                            ("ADDRESS_PROOF", "Address Proof"),
                            ("EDUCATION_CERT", "Education Certificate"),
                            ("OTHER", "Other Document"),
                        ],
                        default="AADHAAR",
                        max_length=30,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Reference/Masked Document Number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_documents",
                        to="common.mediaasset",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "members_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "father_husband_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                ("education", models.CharField(blank=True, max_length=100, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("address_line", models.TextField(blank=True, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="members.member",
                    ),
                ),
                (
                    "photo_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_photos",
                        to="common.mediaasset",
                    ),
                ),
            ],
            options={
                "db_table": "members_profile",
            },
        ),
        migrations.CreateModel(
            name="MembershipCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "qr_token",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_card",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "members_card",
            },
        ),
        migrations.CreateModel(
            name="MemberStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "members_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberTransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_from",
                        to="organization.village",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_requests",
                        to="members.member",
                    ),
                ),
                (
                    "to_village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_to",
                        to="organization.village",
                    ),
                ),
            ],
            options={
                "db_table": "members_transfer_request",
                "ordering": ["-requested_at"],
            },
        ),
    ]
